Fix deprecation warning from threading.Event
python-zk/kazoo pull request #657
Opened 2021-11-12 11:40 UTC by stefreak

Fixes deprecation warning emitted when calling `threading.Event.isSet`

## Why is this needed?

Reasoning:
- `is_set` is supported since Python2.6 (https://docs.python.org/2.7/library/threading.html)
- Starting from Python3.5 docs the `isSet` spelling is not even mentioned anymore (https://docs.python.org/3.5/library/threading.html)
- Python3.10 will give a deprecation warning when the `isSet` spelling is used (https://docs.python.org/3.10/library/threading.html)

## Proposed Changes

- just use is_set over isSet

## Does this PR introduce any breaking change?

- only for users of python version below 2.6; python2.5 is not supported according to setup.py

2021-11-12 12:36 UTC, stefreak commented
I'll be glad to rebase once #652 is merged. Just let me know if I overlook it :)

2021-11-14 23:07 UTC, ceache requested changes
Hi, thank you for your contribution. It looks good to me.  I would only ask that you amend your PR to follow our contribution guideline (https://github.com/python-zk/kazoo/blob/master/CONTRIBUTING.md#git-commit-guidelines) and I would be happy to approve it.

2021-11-15 09:49 UTC, stefreak commented
@ceache sure, thanks a lot for the feedback! I have changed the commit message accordingly.

2021-11-15 18:51 UTC, StephenSorriaux approved these changes
Thank you!

2021-11-16 04:37 UTC, ceache approved these changes

2021-11-29 10:30 UTC, stefreak commented
I rebased with master, hoping that it would run the github actions for my PR, but it didn't; sorry for dismissing your reviews @ceache and @StephenSorriaux

2021-11-29 15:48 UTC, StephenSorriaux commented
Sorry about that, that is actually on me. I will fix it.

2021-11-29 21:49 UTC, ceache submitted a review, later dismissed

2021-12-01 15:25 UTC, StephenSorriaux commented
@stefreak Can you please rebase your PR with the current master that fixes the CI part? Thank you.

2021-12-02 07:32 UTC, stefreak commented
@StephenSorriaux done :)

2021-12-02 15:21 UTC, StephenSorriaux approved these changes

2021-12-02 15:33 UTC, ceache approved these changes

2021-12-02 15:35 UTC, merged